[package]
name = "nft-lending"
version = "1.0.0"
authors = ["aaronvern"]

[addresses]
my_addrx="_"

[dev-addresses]
my_addrx="0xe8ef7448894bd1d95787ceb9bea36e832cc947eb907317a689ec199a0b832052"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token", rev = "mainnet" }
[dev-dependencies]